### ISSUE TITLE
Cargo login doesnt work

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [TalRoni/crates-registry#21]
cargo login --registry crates-registry

yields the following in stdout:
please paste the token found on http://127.0.0.1:5000/me below

I am using your docker container.
The registry runs on a server with port 80 so I have attempted to go to 
http://serverhost.local:80/me
This just yields http 405 method not allowed.

If I try to publish a crate without a token:
with for example the following command:
cargo publish --registry crates-registry

error: no token found for `crates-registry`, please run `cargo login --registry crates-registry`
or use environment variable CARGO_REGISTRIES_CRATES_REGISTRY_TOKEN

How am I supposed to get the token? The frontend only has some rustup toolchain uploader that I dont need. 
I only want to use this as a private crate repository and nothing else.

My ~/cargo/config file looks like this:
```toml
[source.crates-registry]
registry = "http://serverhost.local/git/index"

[registries]
crates-registry = { index = "http://serverhost.local/git/index" }
```

What am I missing?
